### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by Youni2017** [vjaniuw/CardiacModelGenerator#2]
# Feedback:  
Thank you for submitting your project early; bonus points have been awarded accordingly. Your project demonstrates excellent effort, with solid documentation and thoughtful implementation. However, there are some issues with running the code after installation.  

# Problem:  
Could `pip install` but couldn't run. Got the following error:  

(Note: I could import `CardiacModelGenerator`, but there was a problem with your dependency `wx`.)  

```python
from CardiacModelGenerator import CardiacModelGenerator 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/CardiacModelGenerator/CardiacModelGenerator.py", line 9, in <module>
    import wx
  File "/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/wx/_core.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN10wxBoxSizer20InformFirstDirectionEiii'
>>> import CardiacModelGenerator
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jlheller/home/Technical/repos/BIOEN-437/2024-grading/venv/lib/python3.9/site-packages/wx/__init__.py", line 12, in <module>
    __version__ = wx.__version__.VERSION_STRING
AttributeError: partially initialized module 'wx' has no attribute '__version__' (most likely due to a circular import)

**Comment by vjaniuw** [comment]
Hi ZIhan, 

Thank you for doing this. I was wondering if you were using Mac and if so if you followed the steps in the readme where you  first do a pip purge and then make a new virtual environment. 

Moreover, for mac there sometimes is a problem with wx so if you have conda, this also sometimes works: conda install conda-forge::wxpython. Apologies for this there is sometimes a few issues with mac and wx.  I did try this on my mac and it worked but I know online some people did have issues with wx. Unfortunately as I did not have the problem when I used my mac and multiple different virtual environments I was not able to see this.

**Comment by Youni2017** [comment]
Hii Vinay-

Thank you for your detailed explanation and suggestions! If I remember correctly, Prof. Hellerstein is using a Mac, and he’s the one who graded and wrote the comments. This is a great question—looking ahead, it might be helpful to include troubleshooting steps like these in the README to assist others who might encounter similar issues. I truly appreciate your excellent work and thoughtful explanation! 

Here’s to the winter break:)
